### PR TITLE
update-bc-in-jenkinsfile

### PR DESCRIPTION
**Pull request by dongboyan77**
@wanghaoran1988 @cjryan please help review,
according to https://github.com/openshift/origin/blob/master/examples/jenkins/pipeline/samplepipeline.yaml

### CODE REVIEW

**Comment by cjryan** [comment]
@dongboyan77 the change looks good to me - although, since the original repo was jenkins-pipeline-ruby-test, maybe we should consider creating a new repo, called jenkins-pipeline-nodejsmongodb-test, or something similar to differentiate between the two. @wanghaoran1988 what do you think? Thanks!

**Comment by dongboyan77** [comment]
@cjryan good idea, could you fork a jenkins-pipeline-nodejsmongodb-test to openshift-qe repo? please let me know when you done, thanks

**Comment by wanghaoran1988** [comment]
Agree !

**Comment by cjryan** [comment]
@dongboyan77 @wanghaoran1988 thanks so much, I created the following repo, with the above PR changes made:

https://github.com/openshift-qe/jenkins-pipeline-nodejsmongodb-test

Please let me know if there is any trouble with them. Thank you!

**Comment by cjryan** [comment]
@dongboyan77 @wanghaoran1988 thanks so much, I created the following repo, with the above PR changes made:

https://github.com/openshift-qe/jenkins-pipeline-nodejsmongodb-test

Please let me know if there is any trouble with them. Thank you!

**Comment by wanghaoran1988** [comment]
@cjryan Thanks

**Pull request closed without merging**
